version: "3"
services:
  mysql:
    container_name: mysql_sape
    image: getjv/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  backend:
    container_name: backend_sape
    image: getjv/php7.2
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - HTTPD_SERVER_NAME=local
      - HTTPD_DOCUMENT_ROOT_CONTEXT=public
    links:
      - mysql
